[versions]

lettuce = "7.3.0.RELEASE"
protobuf = "4.33.5"
gson = "2.13.2"

[libraries]

lettuce = { group = "io.lettuce", name = "lettuce-core", version.ref = "lettuce" }
protobuf = { group = "com.google.protobuf", name = "protobuf-java", version.ref = "protobuf" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }